update pcap-dnsproxy

diff --git a/packages/chengr28/pcap-dnsproxy/files/pcap-dnsproxy.init b/packages/chengr28/pcap-dnsproxy/files/pcap-dnsproxy.init
--- a/packages/chengr28/pcap-dnsproxy/files/pcap-dnsproxy.init
+++ b/packages/chengr28/pcap-dnsproxy/files/pcap-dnsproxy.init
@@ -5,17 +5,14 @@
 
 START=95
 
-EXTRA_COMMANDS=flush
-EXTRA_HELP="	flush	Flush DNS cache of Pcap_DNSProxy and system (dnsmasq's cache in OP)"
+EXTRA_COMMANDS="flush libver"
+EXTRA_HELP="	flush	Flush DNS cache of Pcap_DNSProxy and system (dnsmasq's cache in OP)
+	libver	Print current version of library"
 
-SERVICE_USE_PID=1
-SERVICE_WRITE_PID=1
 SERVICE_DAEMONIZE=1
 
 PROG="/usr/sbin/Pcap_DNSProxy"
-
 CONFDIR="/etc/pcap-dnsproxy"
-PIDFILE="/var/run/Pcap_DNSProxy.pid"
 
 config_load "pcap-dnsproxy"
 
@@ -31,30 +28,32 @@ config_foreach parse_pcap_dnsproxy 'pcap-dnsproxy'
 
 start() {
 	if [ "1" = "$ENABLED" ] || [ "on" = "$ENABLED" ] || [ "true" = "$ENABLED" ]; then
-		service_start $PROG -c $CONFDIR --disable-daemon
-		RESULT=$?
-		[ $RESULT -eq 0 ] && {
-			echo "Pcap_DNSProxy started successfully"
-		}
-		[ -f $PIDFILE ] && {
+		[ $(ps|grep ${PROG}|grep -v grep|wc -l) -ge 1 ] && {
 			echo "Pcap_DNSProxy is already running"
 			exit 1
 		}
+		service_start $PROG -c $CONFDIR --disable-daemon
+		RESULT=$?
+		[ $RESULT -eq 0 -a $(ps|grep ${PROG}|grep -v grep|wc -l) -ge 1 ] && {
+			echo "Pcap_DNSProxy started successfully"
+		}
 	else
-		echo "Pcap_DNSProxy is disabled"
+		echo "Pcap_DNSProxy is disabled, please check /etc/config/pcap-dnsproxy for more info"
 	fi
 }
 
 stop() {
 	# If you cant stop, use 'killall' instead.
 	# e.g. killall -SIGTERM Pcap_DNSProxy
-	if [ -f $PIDFILE ]; then
+	if [ $(ps|grep ${PROG}|grep -v grep|wc -l) -ge 1 ]; then
 		service_stop $PROG
 		RESULT=$?
-		[ $RESULT -eq 0 ] && {
+		if [ $RESULT -eq 0 -a $(ps|grep ${PROG}|grep -v grep|wc -l) -eq 0 ]; then
 			echo "Pcap_DNSProxy terminated successfully"
-		}
-		rm -f "$PIDFILE"
+		else
+			echo "Failed to terminate Pcap_DNSProxy"
+			echo "Retry or use 'killall -SIG{TERM,KILL} Pcap_DNSProxy' instead"
+		fi
 	else
 		echo "Pcap_DNSProxy is not running"
 	fi
@@ -62,10 +61,18 @@ stop() {
 
 restart() {
 	stop
-	sleep 2s
+	sleep 3s
 	start
 }
 
 flush() {
-	$PROG --flush-dns
+	if [ $(ps|grep ${PROG}|grep -v grep|wc -l) -ge 1 ]; then
+		$PROG --flush-dns
+	else
+		echo "Pcap_DNSProxy is not running"
+	fi
+}
+
+libver() {
+	$PROG --lib-version
 }
