mod

diff --git a/luci/applications/luci-app-dns2socks/root/etc/init.d/dns2socks b/luci/applications/luci-app-dns2socks/root/etc/init.d/dns2socks
--- a/luci/applications/luci-app-dns2socks/root/etc/init.d/dns2socks
+++ b/luci/applications/luci-app-dns2socks/root/etc/init.d/dns2socks
@@ -1,54 +1,39 @@
 #!/bin/sh /etc/rc.common
-
+# Copyright (C) 2006-2011 OpenWrt.org
+# Copyright (C) 2015 GuoGuo <gch981213@gmail.com>
+. /lib/functions.sh
 START=96
-STOP=15
-PIDFILE='/tmp/run/dns2socks.pid'
 
-start()
-{
-	config_load "dns2socks"
-	local enabled dns_ip dns_port socks5_ip socks5_port local_ip local_port socks5_user socks5_pass
-	config_get enabled config enabled
-	config_get dns_ip config dns_ip
-	config_get dns_port config dns_port
-	config_get socks5_ip config socks5_ip
-	config_get socks5_port config socks5_port
-	config_get local_ip config local_ip
-	config_get local_port config local_port
-	config_get socks5_user config socks5_user
-	config_get socks5_pass config socks5_pass
+SERVICE_USE_PID=1
+SERVICE_WRITE_PID=1
+SERVICE_DAEMONIZE=1
 
-	[ $enabled = '0' ] && exit 0
-
-	[ -z "$socks5_ip" ] || [ -z "$dns_ip" ] || [ -z "$local_ip" ] \
-	[ -z "$socks5_port" ] || [ -z "$dns_port" ] || [ -z "$local_port" ] && {
-		echo "missing parameters. check config"
+start() {
+	[ -f /etc/config/dns2socks ] || {
+		echo "You are missing configuration file /etc/config/dns2socks"
 		return 1
 	}
 
-	if [ -f $PIDFILE ];then
-		echo "already started: $PIDFILE exists"
-		return 2
-	fi
+	config_load "dns2socks"
 
-	dns2socks \
-		$socks5_ip:$socks5_port \
-		$dns_ip:$dns_port \
-		$local_ip:$local_port \
-		/q &
-	echo $! > $PIDFILE
+	config_get ENABLED config enabled
 
-	uci del dhcp.@dnsmasq[-1].server
-	uci set dhcp.@dnsmasq[-1].noresolv=1
-	uci add_list dhcp.@dnsmasq[-1].server=127.0.0.1#$local_port
-	uci commit dhcp
-	/etc/init.d/dnsmasq restart
+	[ "$ENABLED" = "0" ] && {
+		echo "dns2socks is disabled."
+		return 1
+	}
+
+	config_get SOCKSUSER config socks5_user
+	config_get SOCKSPASS config socks5_pass
+	config_get SOCKSSERVER config socks5_ip
+	config_get SOCKSPORT config socks5_port
+	config_get DNSSERVER config dns_ip
+	config_get DNSPORT config dns_port
+	config_get LOCALIP config local_ip
+	config_get LOCALPORT config local_port
+	service_start /usr/bin/dns2socks $SOCKSSERVER:$SOCKSPORT $DNSSERVER:${DNSPORT:=53} $LOCALIP:$LOCALPORT
 }
 
-stop()
-{
-	[ -f $PIDFILE ] && {
-		kill -9 `cat $PIDFILE`
-		rm $PIDFILE
-	}
+stop() {
+	service_stop /usr/bin/dns2socks
 }
